name: labshock

networks:
  portal_network:
    driver: bridge

services:
  portal:
    image: zakharbz/labshock-portal:latest
    ports:
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portal-data:/app/config/
    networks:
      - portal_network

  launcher:
      image: zakharbz/labshock-launcher:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./docker-compose.yml:/data/docker-compose.yml:ro
      command: ["tail", "-f", "/dev/null"]

volumes:
  portal-data:
